### ISSUE TITLE
Process error when integrating ecto

### ISSUE THREAD

**Issue by binarylogic** [timberio/timber-elixir-ecto#6]
Relaying for a customer:

---

Hello! I’ve been trying to use `timber_ecto` in one of our apps by following the instructions here: https://github.com/timberio/timber-elixir-ecto

Tried to add this line about telemetry to our repo file, but it’s failing when we try to run `mix ecto.migrate`. Any ideas?

```
defmodule Registrar.Repo do
  use Ecto.Repo,
    otp_app: :registrar,
    adapter: Ecto.Adapters.Postgres

  def init(_, opts) do
     :ok =
     :telemetry.attach(
     "timber-ecto-query-handler",
     [:registrar, :repo, :query],
     &Timber.Ecto.handle_event/4,
     []
     )

    {:ok, opts}
  end
end
```

Error:

```
#!/bin/bash -eo pipefail
mix ecto.create
** (exit) exited in: :gen_server.call(:telemetry_handler_table, {:insert, "timber-ecto-query-handler", [[:registrar, :repo, :query]], &Timber.Ecto.handle_event/4, []})
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib) gen_server.erl:215: :gen_server.call/2
    lib/registrar/repo.ex:8: Registrar.Repo.init/2
    lib/ecto/repo/supervisor.ex:24: Ecto.Repo.Supervisor.runtime_config/4
    lib/registrar/repo.ex:2: Registrar.Repo.config/0
    lib/mix/tasks/ecto.create.ex:53: anonymous fn/3 in Mix.Tasks.Ecto.Create.run/1
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
Exited with code 1
```

**Comment by ashutoshrishi** [comment]
Getting the same thing here

**Comment by binarylogic** [comment]
Hi @ashutoshrishi did you add this to your `Application.start/2` callback? That was what resolved the issue for the above customer. We also updated the [installation instructions](https://github.com/timberio/timber-elixir-ecto#installation) to reflect this. Let me know if that helps.

**Comment by ashutoshrishi** [comment]
@binarylogic yes that worked perfectly now! I still had the attach code in `repo.ex`, but moving it to `application.ex` resolved the issue.

**Comment by binarylogic** [comment]
Great 👍
